// var ps=require("fs")
// // ps.mkdirSync("xyz")
// // ps.writeFileSync("xyz/Jesus.txt","hello")
// // ps.appendFileSync("xyz/jesus.txt","Christ is King")
// // data=ps.readFileSync("xyz/jesus.txt","utf-8")
// // console.log(data)
// // ps.renameSync("xyz/jesus.txt",'xyz/christ.txt')
// // ps.unlinkSync("xyz/christ.txt")
// ps.rmdirSync("xyz")


var ps=require("fs")
// ps.mkdirSync("xyz")
// ps.writeFileSync("xyz/jesus.txt","Hello")
// ps.appendFileSync("xyz/jesus.txt","\n Christ is King")
// jesus=ps.readFileSync("xyz/jesus.txt")
// console.log(jesus.toString())
// ps.renameSync("xyz/jesus.txt",'xyz/mary.txt')
// ps.unlinkSync("xyz/mary.txt")
ps.rmdirSync("xyz")
